export const mockCompanies = [
  {
    id: 1,
    name: 'ALFERT, LLP',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B8103',
    country: 'Kazakhstan',
    logo: '🦅',
    logoColor: 'bg-[#E8F1F8]',
  },
  {
    id: 2,
    name: 'ALPER FRIGO LOGISTICS SERVICES INC',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C5027',
    country: 'Turkey',
    logo: '❄️',
    logoColor: 'bg-teal-50',
  },
  {
    id: 3,
    name: 'ALYANSTRANSTORG',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'Unassigned-1',
    country: 'Russia',
    logo: '🚚',
    logoColor: 'bg-slate-50',
  },
  {
    id: 4,
    name: 'ALYLOGISTICS',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'C9053',
    country: 'Turkey',
    logo: '📦',
    logoColor: 'bg-yellow-100',
  },
  {
    id: 5,
    name: '10CUBITS TECH',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C7107',
    country: 'India',
    logo: '🔵',
    logoColor: 'bg-[#E8F1F8]',
  },
  {
    id: 6,
    name: '1C',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B1021',
    country: 'Russia',
    logo: '🔴',
    logoColor: 'bg-yellow-100',
  },
  {
    id: 7,
    name: '568 LOGISTICS CO., LTD.',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B1157',
    country: 'China',
    logo: '🚢',
    logoColor: 'bg-slate-50',
  },
  {
    id: 8,
    name: 'ABM LOGISTICS',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B1151',
    country: 'Russia',
    logo: '🛫',
    logoColor: 'bg-slate-50',
  },
  {
    id: 9,
    name: 'ABS LOGISTICS',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B1234',
    country: 'Turkey',
    logo: '📊',
    logoColor: 'bg-[#E8F1F8]',
  },
  {
    id: 10,
    name: 'ACE WAYS',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C5678',
    country: 'Russia',
    logo: '🏔️',
    logoColor: 'bg-slate-50',
  },
  {
    id: 11,
    name: 'ADY EXPRESS LLC',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B8017',
    country: 'Russia',
    logo: '🚀',
    logoColor: 'bg-slate-50',
  },
  {
    id: 12,
    name: 'TROYKA ULUSLARARASI NAKLIYAT VE TICARET A.S. (TURKIYE)',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'C2134',
    country: 'Turkey',
    logo: '🛣️',
    logoColor: 'bg-slate-50',
  },
  {
    id: 13,
    name: '#RAKETADIGITAL',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C7143',
    country: 'Russia',
    logo: '🚀',
    logoColor: 'bg-purple-50',
  },
  {
    id: 14,
    name: 'OPTICORE',
    pavilion: 'Pavilion 3 Hall 13',
    stand: 'A2065',
    country: 'Russia',
    logo: '🌐',
    logoColor: 'bg-orange-50',
  },
  {
    id: 15,
    name: 'AERO SERVICES',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B9123',
    country: 'Russia',
    logo: '✈️',
    logoColor: 'bg-red-50',
  },
  {
    id: 16,
    name: 'ZEST LOGISTICS',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C4567',
    country: 'Kazakhstan',
    logo: '⚡',
    logoColor: 'bg-yellow-50',
  },
  {
    id: 17,
    name: 'NEXUS TRANSPORT',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B5678',
    country: 'Turkey',
    logo: '🔗',
    logoColor: 'bg-[#E8F1F8]',
  },
  {
    id: 18,
    name: 'GLOBAL FREIGHT',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C8901',
    country: 'Russia',
    logo: '🌍',
    logoColor: 'bg-green-50',
  },
  {
    id: 19,
    name: 'SWIFT CARGO',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B2345',
    country: 'China',
    logo: '📦',
    logoColor: 'bg-slate-50',
  },
  {
    id: 20,
    name: 'PRIME LOGISTICS',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C6789',
    country: 'India',
    logo: '👑',
    logoColor: 'bg-purple-50',
  },
  {
    id: 21,
    name: 'HORIZON TRANSPORT',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B3456',
    country: 'Russia',
    logo: '🌅',
    logoColor: 'bg-orange-50',
  },
  {
    id: 22,
    name: 'ZENITH CARGO',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C9012',
    country: 'Turkey',
    logo: '⬆️',
    logoColor: 'bg-slate-50',
  },
  {
    id: 23,
    name: 'VELOCITY FREIGHT',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B4567',
    country: 'Kazakhstan',
    logo: '💨',
    logoColor: 'bg-[#E8F1F8]',
  },
  {
    id: 24,
    name: 'ATLAS LOGISTICS',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C3456',
    country: 'Russia',
    logo: '🗺️',
    logoColor: 'bg-slate-50',
  },
  {
    id: 25,
    name: 'MERIDIAN SERVICES',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B5678',
    country: 'China',
    logo: '🧭',
    logoColor: 'bg-teal-50',
  },
  {
    id: 26,
    name: 'MOMENTUM TRANSPORT',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C7890',
    country: 'India',
    logo: '💪',
    logoColor: 'bg-red-50',
  },
  {
    id: 27,
    name: 'PARADIGM LOGISTICS',
    pavilion: 'Pavilion 3 Hall 14',
    stand: 'B6789',
    country: 'Russia',
    logo: '🎯',
    logoColor: 'bg-yellow-50',
  },
  {
    id: 28,
    name: 'QUANTUM FREIGHT',
    pavilion: 'Pavilion 3 Hall 15',
    stand: 'C1234',
    country: 'Turkey',
    logo: '⚛️',
    logoColor: 'bg-purple-50',
  },
]
